(cl:in-package rcs_msg_wrapper-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME_LABEL-VAL
          TIME_LABEL
          GLOBAL_X-VAL
          GLOBAL_X
          GLOBAL_Y-VAL
          GLOBAL_Y
          GLOBAL_H-VAL
          GLOBAL_H
          ZONE-VAL
          ZONE
          LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          HEADING-VAL
          HEADING
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          GLOBAL_VX-VAL
          GLOBAL_VX
          GLOBAL_VY-VAL
          GLOBAL_VY
          GLOBAL_VZ-VAL
          GLOBAL_VZ
          GLOBAL_WX-VAL
          GLOBAL_WX
          GLOBAL_WY-VAL
          GLOBAL_WY
          GLOBAL_WZ-VAL
          GLOBAL_WZ
          MILEAGE-VAL
          MILEAGE
          ID-VAL
          ID
))